apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: estafette-ci-api
  namespace: estafette-ci-jobs
  labels:
    app: estafette-ci-api
rules:
- apiGroups: ["batch"] # "" indicates the core API group
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: [""] # "" indicates the core API group
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups: [""] # "" indicates the core API group
  resources:
  - configmaps
  verbs:
  - get
  - list
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: estafette-ci-api
  namespace: estafette-ci-jobs
  labels:
    app: estafette-ci-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: estafette-ci-api
  namespace: estafette-ci-jobs
subjects:
- kind: ServiceAccount
  name: estafette-ci-api
  namespace: estafette
