# Default values for estafette-ci.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#
# APPLICATION SETTINGS
#

secret:
  # the aes-256 key to encrypt/decrypt estafette secrets
  decryptionKey:

  # private key file for github app to communicate with the github api
  githubPrivateKey:

jobs:
  # the namespace in which build/release jobs are created
  namespace:

integrations:
  github:
    privateKeyPath: /secrets/private-key.pem
    appID:
    clientID:
    clientSecret:
    webhookSecret:

  bitbucket:
    apiKey: 
    appOAuthKey: 
    appOAuthSecret: 

  slack:
    clientID: 
    clientSecret:
    appVerificationToken:
    appOAuthAccessToken:

  pubsub:
    defaultProject:
    endpoint:
    audience:
    serviceAccountEmail:
    subscriptionNameSuffix:
    subscriptionIdleExpirationDays: 365

  prometheus:
    serverURL: http://prometheus-server.monitoring.svc.cluster.local
    scrapeIntervalSeconds: 10

  bigquery:
    enable:
    projectID:
    dataset:

apiServer:
  baseURL:
  serviceURL:

auth:
  iap:
    enable:
    audience:
  apiKey:

jobs:
  namespace:
  minCPUCores:
  maxCPUCores:
  cpuRequestRatio:
  minMemoryBytes:
  maxMemoryBytes:
  memoryRequestRatio:

database:
  databaseName:
  host:
  insecure:
  certificateDir:
  port:
  user:
  password:

credentials:
- name:
  type: 'container-registry'
  repository:
  private: false
  username:
  password:

trustedImages:
- path: extensions/git-clone
  injectedCredentialTypes:
  - bitbucket-api-token
  - github-api-token
- path: extensions/git-trigger
  injectedCredentialTypes:
  - bitbucket-api-token
  - github-api-token
- path: extensions/docker
  runDocker: true
  injectedCredentialTypes:
  - container-registry
- path: extensions/prefetch
  runDocker: true
  injectedCredentialTypes:
  - container-registry
- path: extensions/gke
  injectedCredentialTypes:
  - kubernetes-engine
- path: extensions/gcs
  injectedCredentialTypes:
  - kubernetes-engine
- path: extensions/cloud-function
  injectedCredentialTypes:
  - kubernetes-engine
- path: extensions/bitbucket-status
  injectedCredentialTypes:
  - bitbucket-api-token
- path: extensions/github-status
  injectedCredentialTypes:
  - github-api-token
- path: extensions/github-release
  injectedCredentialTypes:
  - github-api-token
- path: extensions/slack-build-status
  injectedCredentialTypes:
  - slack-webhook
- path: extensions/npm-audit
  injectedCredentialTypes:
  - slack-webhook
- path: extensions/dotnet
  injectedCredentialTypes:
  - nuget-server
  - sonarqube-server
- path: estafette/estafette-ci-builder
  runPrivileged: true
- path: extensions/cloudflare-purge
  injectedCredentialTypes:
  - cloudflare
- path: bsycorp/kind
  runPrivileged: true

registryMirror:
registryMdindMtuirror:
dindBip:
dindNetwork:
  name:
  subnet:
  gateway:

#
# GENERIC SETTINGS
#

replicaCount: 1

image:
  repository: estafette/estafette-ci-api
  # The tag can be set to override the appVersion getting used as the image tag
  tag:
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

rbac:
  # Specifies whether roles and bindings should be created
  enable: true

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: 60m
    memory: 236Mi
  limits:
    cpu: 120m
    memory: 472Mi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 10
      preference:
        matchExpressions:
        - key: cloud.google.com/gke-preemptible
          operator: In
          values:
          - "true"

# pass (additional) arguments to the container
extraArgs: []

# use to set extra environment variables
extraEnv: {}

# use to add extra labels
extraLabels: {}

# use to add extra labels to podspec for getting their values in prometheus
extraPodLabels: {}
