apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Name}}-slack
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # slack doesn't have a fixed list of exit ips, they run on AWS without using any form of predictable exit ips
    nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "{{.NginxIngressClientBodyBufferSize}}"
    nginx.ingress.kubernetes.io/proxy-body-size: "{{.NginxIngressProxyBodySize}}"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "{{.NginxIngressProxyBuffersNumber}}"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "{{.NginxIngressProxyBufferSize}}"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{.NginxIngressProxyConnectTimeout}}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{.NginxIngressProxySendTimeout}}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{.NginxIngressProxyReadTimeout}}"
    nginx.ingress.kubernetes.io/default-backend: "{{.Name}}"
    estafette.io/cloudflare-dns: "true"
    estafette.io/cloudflare-proxy: "true"
    estafette.io/cloudflare-hostnames: "{{.ManifestData.IntegrationsHostname}}"
spec:
  tls:
  - hosts:
    - {{.ManifestData.IntegrationsHostname}}
    secretName: {{.Name}}-integrations-letsencrypt-certificate
  rules:
  - host: {{.ManifestData.IntegrationsHostname}}
    http:
      paths:
      - path: /api/integrations/slack/slash
        backend:
          serviceName: {{.Name}}
          servicePort: https