apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Name}}-bitbucket
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/whitelist-source-range: "104.192.136.0/21,34.198.203.127/32,34.198.178.64/32,34.198.32.85/32"
    estafette.io/cloudflare-dns: "true"
    estafette.io/cloudflare-proxy: "true"
    estafette.io/cloudflare-hostnames: "{{.ManifestData.IntegrationsHostname}}"
spec:
  tls:
  - hosts:
    - {{.ManifestData.IntegrationsHostname}}
    secretName: {{.Name}}-integrations-letsencrypt-certificate
  rules:
  - host: {{.ManifestData.IntegrationsHostname}}
    http:
      paths:
      - path: /api/integrations/bitbucket
        backend:
          serviceName: {{.Name}}
          servicePort: https