apiVersion: v1
kind: Secret
metadata:
  name: {{ include "estafette-letsencrypt-certificate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-letsencrypt-certificate.labels" . | indent 4 }}
type: Opaque
data:
  decryptionKey: {{.Values.secret.decryptionKey | toString | b64enc}}