apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-ci-api.labels" . | indent 4 }}
data:
  config.yaml: |-
    {{- with .Values.integrations }}
    integrations:
      {{- with .github }}
      github:
        privateKeyPath: {{.privateKeyPath}}
        appID: {{.appID}}
        clientID: {{.clientID}}
        clientSecret: {{.clientSecret}}
        webhookSecret: {{.webhookSecret}}
      {{- end }}

      {{- with .bitbucket }}
      bitbucket:
        apiKey: {{.apiKey}}
        appOAuthKey: {{.appOAuthKey}}
        appOAuthSecret: {{.appOAuthSecret}}
      {{- end }}

      {{- with .slack }}
      slack:
        clientID: {{.clientID}}
        clientSecret: {{.clientSecret}}
        appVerificationToken: {{.appVerificationToken}}
        appOAuthAccessToken: {{.appOAuthAccessToken}}
      {{- end }}

      {{- with .pubsub }}
      pubsub:
        defaultProject: {{.defaultProject}}
        endpoint: {{.endpoint}}
        audience: {{.audience}}
        serviceAccountEmail: {{.serviceAccountEmail}}
        subscriptionNameSuffix: {{.subscriptionNameSuffix}}
        subscriptionIdleExpirationDays: 365
      {{- end }}

      {{- with .prometheus }}
      prometheus:
        serverURL: {{.serverURL}}
        scrapeIntervalSeconds: {{.scrapeIntervalSeconds}}
      {{- end }}

      {{- with .bigquery }}
      bigquery:
        enable: {{.enable}}
        projectID: {{.projectID}}
        dataset: {{.dataset}}
      {{- end }}
    {{- end }}

    {{- with .Values.apiServer }}
    apiServer:
      baseURL: {{.baseURL}}
      serviceURL: {{.serviceURL}}
    {{- end }}

    {{- with .Values.auth }}
    auth:
      {{- with .iap }}
      iap:
        enable: {{.enable}}
        audience: {{.audience}}
      {{- end }}
      apiKey: {{.apiKey}}
    {{- end }}

    {{- with .Values.jobs }}
    jobs:
      namespace: {{.namespace}}
      minCPUCores: {{.minCPUCores}}
      maxCPUCores: {{.maxCPUCores}}
      cpuRequestRatio: {{.cpuRequestRatio}}
      minMemoryBytes: {{.minMemoryBytes}}
      maxMemoryBytes: {{.maxMemoryBytes}}
      memoryRequestRatio: {{.memoryRequestRatio}}
    {{- end }}

    {{- with .Values.apiServer }}
    database:
      databaseName: {{.databaseName}}
      host: {{.host}}
      insecure: {{.insecure}}
      certificateDir: {{.certificateDir}}
      port: {{.port}}
      user: {{.user}}
      password: {{.password}}
    {{- end }}

    {{- with .Values.credentials }}
    credentials:
    {{- toYaml . | nindent 4 }}
    {{- end }}

    {{- with .Values.trustedImages }}
    trustedImages:
    {{- toYaml . | nindent 4 }}
    {{- end }}


    {{- with .Values.registryMirror }}
    registryMirror: {{.}}
    {{- end }}
    {{- with .Values.dindMtu }}
    registryMdindMtuirror: {{.}}
    {{- end }}
    {{- with .Values.dindBip }}
    dindBip: {{.}}
    {{- end }}
    {{- with .Values.dindNetwork }}
    dindNetwork:
      name: {{.name}}
      subnet: {{.subnet}}
      gateway: {{.gateway}}
    {{- end }}