apiVersion: v1
kind: Secret
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-ci-api.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.secret.valuesAreBase64Encoded }}
  decryptionKey: {{.Values.secret.decryptionKey | toString}}
  {{- with .Values.secret.githubPrivateKey }}
  githubPrivateKey: {{ . | toString}}
  {{- end }}
  {{- else }}
  decryptionKey: {{.Values.secret.decryptionKey | toString | b64enc}}
  {{- with .Values.secret.githubPrivateKey }}
  githubPrivateKey: {{ . | toString | b64enc}}
  {{- end }}
  {{- end }}