integrations:
  github:
    privateKeyPath: /github-app-key/private-key.pem
    appID: 15
    clientID: asdas2342
    clientSecret: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)
    webhookSecret: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)
    eventChannelBufferSize: 100
    maxWorkers: 5

  bitbucket:
    apiKey: sd9ewiwuejkwejkewk
    appOAuthKey: 2390w3e90jdsk
    appOAuthSecret: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)
    eventChannelBufferSize: 100
    maxWorkers: 5

  slack:
    clientID: d9ew90weoijewjke
    clientSecret: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)
    appVerificationToken: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)
    appOAuthAccessToken: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)
    eventChannelBufferSize: 100
    maxWorkers: 5

apiServer:
  baseURL: https://ci.estafette.io/
  serviceURL: http://estafette-ci-api.estafette.svc.cluster.local/
  eventChannelBufferSize: 100
  maxWorkers: 5

auth:
  iap:
    enable: true
    audience: /projects/***/global/backendServices/***
  apiKey: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)

database:
  databaseName: estafette_ci_api
  host: cockroachdb-public.estafette.svc.cluster.local
  insecure: true
  certificateDir: /cockroachdb-certificates/cockroachdb.crt
  port: 26257
  user: myuser
  password: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)

credentials:
- name: container-registry-extensions
  type: container-registry
  repository: extensions
  username: username
  password: secret
- name: container-registry-estafette
  type: container-registry
  repository: estafette
  username: username
  password: secret
- name: gke-estafette-production
  type: kubernetes-engine
  project: estafette-production
  region: europe-west2
  cluster: production-europe-west2
  defaultNamespace: estafette
  serviceAccountKeyfile: '{}'
- name: gke-estafette-development
  type: kubernetes-engine
  project: estafette-development
  cluster: development-europe-west2
  region: europe-west2
  defaultNamespace: estafette
  serviceAccountKeyfile: '{}'
- name: bitbucket-api-token
  type: bitbucket-api-token
  token: sometoken
- name: github-api-token
  type: github-api-token
  token: sometoken
- name: slack-webhook-estafette
  type: slack-webhook
  workspace: estafette
  webhook: somewebhookurl

trustedImages:
- path: extensions/docker
  runDocker: true
  injectedCredentialTypes:
  - container-registry
- path: extensions/gke
  injectedCredentialTypes:
  - kubernetes-engine
- path: extensions/bitbucket-status
  injectedCredentialTypes:
  - bitbucket-api-token
- path: extensions/github-status
  injectedCredentialTypes:
  - github-api-token
- path: extensions/slack-build-status
  injectedCredentialTypes:
  - slack-webhook
- path: docker
  runDocker: true
- path: multiple-git-sources-test
  injectedCredentialTypes:
  - bitbucket-api-token
  - github-api-token